name: Unit test


on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html coveralls requests coverage  

    - name: Run tests
      run: |
        cd test
        coverage run -m pytest unit-test.py --html=test-report.html
        
    
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
      

    # Upload test report as artifact
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report.html
        path: test

    # Upload coverage report as artifact
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: test    

        