name: Run unit test

# Evento di trigger: Esegui la pipeline su ogni push
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice dal repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Sostituisci con la versione di Python che desideri usare

    # Installa le dipendenze
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html requests  # Installa pytest e pytest-html
        # Aggiungi altri comandi di installazione se necessario

    # Esegui i test
    - name: Run tests
      run: |
        cd test
        pytest unit-test.py --html=test-report.html

    # Upload del report dei test come artefatto
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html