name: Unit test

# Evento di trigger: Esegui la pipeline su ogni push
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice dal repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Sostituisci con la versione di Python che desideri usare

    # Installa le dipendenze
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html coveralls requests coverage  # Installa pytest e pytest-html
        # Aggiungi altri comandi di installazione se necessario

    # Esegui i test
    - name: Run tests
      run: |
        coveralls
      #  coverage run -m pytest unit-test.py --html=test-report.html
        
      #  coverage html -d coverage-report
    
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
      

    # Upload del report dei test come artefatto
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report.html
        path: test

    # Upload del report dei test come artefatto
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: test    

        